import type { Mission, FlightOption } from "./types";

const baseTimeline = (statusIdx: number) => {
  const steps = [
    { id: "created", label: "Mission created", detail: "Intake completed" },
    { id: "paid", label: "Payment approved", detail: "Funds in mission wallet" },
    { id: "matched", label: "Courier matched", detail: "Verified courier confirmed" },
    { id: "flight-selected", label: "Flight selected", detail: "Route locked" },
    { id: "flight-booked", label: "Flight booked", detail: "Ticket reserved by F1" },
    { id: "to-pickup", label: "Courier en route to pickup", detail: "GPS active" },
    { id: "picked", label: "Pickup confirmed", detail: "Item secured & sealed" },
    { id: "airport-in", label: "Courier at airport", detail: "Check-in complete" },
    { id: "boarded", label: "Flight boarded", detail: "On board" },
    { id: "in-air", label: "Flight in air", detail: "Tracking by flight" },
    { id: "landed", label: "Flight landed", detail: "Customs in progress" },
    { id: "customs", label: "Customs cleared", detail: "Released" },
    { id: "out-for-delivery", label: "Out for delivery", detail: "Heading to receiver" },
    { id: "delivered", label: "Receiver confirmed", detail: "Signed at door" },
    { id: "sealed", label: "Proof Pack sealed", detail: "Tamper-evident" },
    { id: "paid-out", label: "Courier paid", detail: "Payout released" },
  ];
  return steps.map((s, i) => ({
    ...s,
    status: i < statusIdx ? ("done" as const) : i === statusIdx ? ("active" as const) : ("pending" as const),
    time: i < statusIdx ? new Date(Date.now() - (statusIdx - i) * 1000 * 60 * 23).toLocaleTimeString([], { hour: "2-digit", minute: "2-digit" }) : undefined,
  }));
};

export const SEED_MISSIONS: Mission[] = [
  {
    id: "m-7421",
    shortId: "F1-7421",
    status: "green",
    createdAt: new Date(Date.now() - 1000 * 60 * 48).toISOString(),
    item: { type: "Automotive part", name: "Engine sensor module", weightKg: 1.8, sizeCm: "22×14×8", valueUsd: 1450, notes: "Anti-static bag" },
    pickup: { address: "1421 Rosa Parks Blvd, Detroit, MI", contact: "L. Martinez · +1 313 555 0148", city: "Detroit", airport: "DTW", window: "Today, 11:30–12:00" },
    delivery: { address: "Av. Constitución 200, Monterrey, NL", contact: "R. Salinas · +52 81 5550 9921", city: "Monterrey", airport: "MTY", deadline: "Tomorrow, 09:00" },
    courier: { name: "Marcus T.", initials: "MT", rating: 4.96, trips: 213, verified: true },
    flight: { number: "AM 0407", carrier: "Aeromexico", from: "DTW", to: "MTY", departLocal: "14:55", arriveLocal: "18:42", status: "booked" },
    price: { courier: 850, flight: 612, ground: 95, compliance: 60, insurance: 45, platform: 138, total: 1800 },
    precheck: {
      light: "green",
      flags: [
        { label: "Carry-on eligible", level: "ok" },
        { label: "No restricted goods", level: "ok" },
        { label: "Mexico import docs ready", level: "ok" },
        { label: "Courier visa valid", level: "ok" },
      ],
    },
    timeline: baseTimeline(6),
    proof: {
      sealed: false,
      items: [
        { label: "Pickup photo", ok: true },
        { label: "Item seal photo", ok: true },
        { label: "Airport check-in stamp", ok: false },
        { label: "Boarding pass", ok: false },
        { label: "Customs entry stamp", ok: false },
        { label: "Delivery photo", ok: false },
        { label: "Receiver signature", ok: false },
        { label: "Chain of custody log", ok: false },
      ],
    },
  },
  {
    id: "m-7388",
    shortId: "F1-7388",
    status: "yellow",
    createdAt: new Date(Date.now() - 1000 * 60 * 90).toISOString(),
    item: { type: "Prototype", name: "Robotics arm prototype", weightKg: 6.2, sizeCm: "55×30×22", valueUsd: 8200 },
    pickup: { address: "500 Boylston St, Boston, MA", contact: "K. Owen · +1 617 555 0102", city: "Boston", airport: "BOS", window: "Today, 16:00–16:30" },
    delivery: { address: "Königsallee 22, Düsseldorf", contact: "J. Becker · +49 211 5550 8810", city: "Düsseldorf", airport: "DUS", deadline: "Tomorrow, 18:00" },
    courier: { name: "Priya R.", initials: "PR", rating: 4.91, trips: 96, verified: true },
    flight: { number: "LH 423", carrier: "Lufthansa", from: "BOS", to: "FRA → DUS", departLocal: "20:10", arriveLocal: "11:30+1", status: "reserved" },
    price: { courier: 1600, flight: 1480, ground: 180, compliance: 220, insurance: 120, platform: 300, total: 3900 },
    precheck: {
      light: "yellow",
      flags: [
        { label: "Commercial invoice", level: "warn", note: "Missing — upload required" },
        { label: "EU import documentation", level: "warn", note: "Review needed" },
        { label: "Carry-on / checked", level: "ok", note: "Checked baggage approved" },
        { label: "Courier passport valid", level: "ok" },
      ],
    },
    timeline: baseTimeline(2),
    proof: {
      sealed: false,
      items: [
        { label: "Commercial invoice", ok: false },
        { label: "EU import declaration", ok: false },
        { label: "Pickup photo", ok: false },
        { label: "Delivery photo", ok: false },
      ],
    },
    notes: "Awaiting commercial invoice from shipper.",
  },
  {
    id: "m-7361",
    shortId: "F1-7361",
    status: "red",
    createdAt: new Date(Date.now() - 1000 * 60 * 130).toISOString(),
    item: { type: "Electronics", name: "Industrial UPS battery pack", weightKg: 14, valueUsd: 2200, notes: "Lithium-ion, 280 Wh" },
    pickup: { address: "9 Wai Yip St, Kwun Tong, Hong Kong", contact: "T. Wong · +852 5550 4421", city: "Hong Kong", airport: "HKG", window: "Tomorrow, 09:00" },
    delivery: { address: "1 Market St, San Francisco, CA", contact: "A. Patel · +1 415 555 0177", city: "San Francisco", airport: "SFO", deadline: "+48 hours" },
    price: { courier: 0, flight: 0, ground: 0, compliance: 0, insurance: 0, platform: 0, total: 0 },
    precheck: {
      light: "red",
      flags: [
        { label: "Lithium battery > 100 Wh", level: "block", note: "Cannot move as onboard courier" },
        { label: "IATA carry restriction", level: "block", note: "Air carrier prohibition" },
        { label: "Safer alternative", level: "warn", note: "Suggest dangerous-goods air freight" },
      ],
    },
    timeline: baseTimeline(0),
    proof: { sealed: false, items: [] },
    notes: "AI Pre-Check blocked. Compliance team to recommend alternative.",
  },
  {
    id: "m-7299",
    shortId: "F1-7299",
    status: "complete",
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 18).toISOString(),
    item: { type: "Documents", name: "Signed M&A closing binder", weightKg: 1.2, valueUsd: 25000 },
    pickup: { address: "Canary Wharf, London", contact: "S. Holloway · +44 20 5550 0091", city: "London", airport: "LHR", window: "Yesterday, 08:00" },
    delivery: { address: "Park Avenue, New York, NY", contact: "B. Klein · +1 212 555 0119", city: "New York", airport: "JFK", deadline: "Yesterday, 17:00" },
    courier: { name: "Henrik S.", initials: "HS", rating: 4.99, trips: 412, verified: true },
    flight: { number: "BA 175", carrier: "British Airways", from: "LHR", to: "JFK", departLocal: "10:25", arriveLocal: "13:35", status: "landed" },
    price: { courier: 2100, flight: 1980, ground: 220, compliance: 140, insurance: 180, platform: 380, total: 5000 },
    precheck: { light: "green", flags: [{ label: "All checks passed", level: "ok" }] },
    timeline: baseTimeline(16),
    proof: {
      sealed: true,
      items: [
        { label: "Pickup photo", ok: true },
        { label: "Item seal photo", ok: true },
        { label: "Boarding pass", ok: true },
        { label: "Flight evidence", ok: true },
        { label: "Customs entry stamp", ok: true },
        { label: "Delivery photo", ok: true },
        { label: "Receiver signature", ok: true },
        { label: "Chain of custody log", ok: true },
      ],
    },
  },
  {
    id: "m-7256",
    shortId: "F1-7256",
    status: "delay",
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 5).toISOString(),
    item: { type: "Medical device", name: "Cardiac mapping catheter", weightKg: 2.4, valueUsd: 6800 },
    pickup: { address: "Mission Bay, San Francisco, CA", contact: "Dr. Lee · +1 415 555 0901", city: "San Francisco", airport: "SFO", window: "Today, 06:30" },
    delivery: { address: "Charité, Berlin", contact: "Dr. Vogel · +49 30 5550 7711", city: "Berlin", airport: "BER", deadline: "Tomorrow, 14:00" },
    courier: { name: "Aisha M.", initials: "AM", rating: 4.94, trips: 178, verified: true },
    flight: { number: "UA 935 → LH 182", carrier: "United / Lufthansa", from: "SFO", to: "FRA → BER", departLocal: "15:40", arriveLocal: "14:20+1", status: "delayed" },
    price: { courier: 2400, flight: 2150, ground: 240, compliance: 180, insurance: 220, platform: 410, total: 5600 },
    precheck: { light: "green", flags: [{ label: "Medical non-hazmat cleared", level: "ok" }] },
    timeline: baseTimeline(9),
    proof: {
      sealed: false,
      items: [
        { label: "Pickup photo", ok: true },
        { label: "Boarding pass", ok: true },
        { label: "Backup route activated", ok: true },
      ],
    },
    notes: "Connecting flight delayed 90 min. Backup route activated via FRA→BER.",
  },
];

export const FLIGHT_OPTIONS: FlightOption[] = [
  {
    id: "fastest",
    title: "Fastest",
    carrier: "Aeromexico",
    flightNo: "AM 0407",
    from: "DTW",
    to: "MTY",
    departLocal: "14:55",
    arriveLocal: "18:42",
    durationMin: 287,
    stops: 0,
    riskLabel: "Low",
    pickupEtaMin: 45,
    deliveryEtaHours: 7,
    price: 1800,
    recommended: true,
  },
  {
    id: "value",
    title: "Best Value",
    carrier: "Delta",
    flightNo: "DL 2210",
    from: "DTW",
    to: "MTY",
    departLocal: "16:30",
    arriveLocal: "21:10",
    durationMin: 340,
    stops: 1,
    riskLabel: "Medium",
    pickupEtaMin: 60,
    deliveryEtaHours: 9,
    price: 1490,
  },
  {
    id: "secure",
    title: "Most Secure",
    carrier: "American",
    flightNo: "AA 1188",
    from: "DTW",
    to: "MTY",
    departLocal: "13:20",
    arriveLocal: "19:05",
    durationMin: 405,
    stops: 1,
    riskLabel: "Low",
    pickupEtaMin: 40,
    deliveryEtaHours: 8,
    price: 2050,
  },
];

export const COURIER_MISSION_PING = {
  shortId: "F1-7421",
  route: "Detroit → Monterrey",
  itemType: "Automotive sensor",
  payout: 850,
  pickupInMin: 90,
  flight: "AM 0407 · DTW 14:55 → MTY 18:42",
  bookedByF1: true,
  requirements: [
    { label: "Passport valid", ok: true },
    { label: "Mexico entry eligible", ok: true },
    { label: "Carry-on compatible", ok: true },
    { label: "Identity verified", ok: true },
  ],
};
